oc_user:
    resource: "@OCUserBundle/Resources/config/routing.yml"
    prefix:   /

rest:
    resource: "@RestBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
